---
title: "Portland area temperature - updated every hour"
author: "Esteban"
date: "7/28/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}

body
html
	height 100%
	margin 0

#map
	width 100%
	height 100%

```


```{r load_packages, include=FALSE, message=F, warning=F}

if (!require(pacman)) {
  install.packages("pacman")
  library(pacman)
}

p_load(plyr, leaflet.extras
       ,dplyr
       ,sp
       ,sf
       ,leaflet
       ,httr
       ,rgdal
       ,gdata
       ,data.table
       ,jsonlite
       ,tidyr
       ,s2dverification
       ,grDevices
)


```



```{r obtain clean ready data, echo=FALSE, warning=FALSE, message=F}

# get a bounding box to use in the geojson call
##############################################################################################

# Make the study area (Practicing using Portland...)
# read in shapefile of Tacoma
# pdx <- readOGR(dsn = "shape/ugb.shp")
# projection(pdx)
# 
# # CRS for leaflet
# wgs84 <- '+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0'
# 
# # convert to meters projected
# pdx <- spTransform(pdx, CRSobj = CRS(wgs84))
# 
# # make a bounding box
# bb <- as(raster::extent(bbox(pdx)), "SpatialPolygons")
# proj4string(bb) <- proj4string(pdx)
# extent(bb)

#########################################################################################


# get request for data
#########################################################################################


# trying to do a get request for synoptic data....
path <- "https://api.synopticdata.com/v2/stations/timeseries"
timeformat <- "timeformat=%s"
bbox <- "-123.15,45.3,-122.37,45.65"   # [lonmin,latmin,lonmax,latmax]
vars <- "air_temp"
token <- "4e7d3c4398e94b82bd8a5c64c2f8639a"
units <- "english"
output <- "geojson"

request <- GET(url = path, 
               query = list(
                 token = token,
                 bbox = bbox,
                 vars = vars,
                 recent = 60, # minutes since the last report...
                 units = units,
                 output = output)
)

# clean up the data!!
####################################################################################

# from philip AAAAAAANNNNDD of course this is the three
# THREE pieces of code that I needed. 
url <- request$url
r <- fromJSON(url)
df <- r$features

# df now says it has three columns, but it actually has way more. 
# this is due to atomic/nonatomic issues.
# This bit of code should solve the issue...
dt <- data.table(df, stringsAsFactors = FALSE)

# clean the data table???
dt <- dt %>% dplyr::select(c(7, 10, 12, 14, 17, 20)) 
# Take "properties" out of the column header names...
names(dt) = gsub(pattern = "properties.", replacement = "", x = names(dt))

# as dataframe
df <- as.data.frame(dt)

# unnest!!!!
df <- unnest(df, c(air_temp, date_times))

# convert some columns to numeric...
df$longitude <- as.numeric(as.character(df$longitude))
df$latitude <- as.numeric(as.character(df$latitude))
df$air_temp <- as.numeric(as.character(df$air_temp))

# date as a date (INCLUDE -6 HOURS!!!!!)
df$date_times <- as.POSIXct(strptime(df$date_times, format = "%Y-%m-%dT%H:%M")) 
df$date_times <- df$date_times - 21600


####################################################################################

# Prepare to MAP THE DATA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# leaflet crs
wgs84 <- "+proj=longlat +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0"

# Make coordinates from lat, lon and turn them into spatial points
coords <- cbind(df$longitude, df$latitude)
sp <- SpatialPoints(coords)

spdf <- SpatialPointsDataFrame(coords, df, proj4string = CRS(wgs84))

###########################################################################


# MAP IT!!!!!!!!!!!!!

# color ramp
# TODO fix to make this specific to ALL TEMP, not just temp showing...
# Create a continuous palette function
pal <- colorNumeric(
  palette = 'YlOrRd',
  domain = df$air_temp)
# pal <- grDevices::colorRampPalette(c("yellow", "orange", "red"))


# popup 
temp_pop <- paste0(
  "<b>Air Temperature (F): </b>", spdf$air_temp, "<br>",
  "<b>Location: </b>", spdf$name, "<br>",
  "<b>ID: </b>", spdf$stid, "<br>",
  "<b>Time: </b>", spdf$date_times
)

```


```{r leaflet, echo=FALSE, warning=FALSE, message=F}

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = spdf 
                   ,fillColor = pal(df$air_temp)
                   ,fillOpacity = 0.7
                   ,radius = 7
                   ,color = 'black'
                   ,weight = 0.2
                   ,popup = temp_pop) 



```


